/* eslint-disable import/prefer-default-export */

// application
import { IBrand } from '~/interfaces/brand';

export const brands: IBrand[] = [
    {
        id: 1,
        slug: 'aim-parts',
        name: 'AimParts',
        country: 'TG',
        image: '/images/brands/brand-1.png',
        latitude: 6.1375,
        longitude: 1.2123,
        shopId: 101,
    },
    {
        id: 2,
        slug: 'wind-engine',
        name: 'WindEngine',
        country: 'TG',
        image: '/images/brands/brand-2.png',
        latitude: 6.1800,
        longitude: 1.2300,
        shopId: 102,
    },
    {
        id: 3,
        slug: 'turbo-electric',
        name: 'TurboElectric',
        country: 'GH',
        image: '/images/brands/brand-3.png',
        latitude: 5.6037,
        longitude: -0.1870,
        shopId: 103,
    },
    {
        id: 4,
        slug: 'start-one',
        name: 'StartOne',
        country: 'GH',
        image: '/images/brands/brand-4.png',
        latitude: 6.6885,
        longitude: -1.6244,
        shopId: 104,
    },
    {
        id: 5,
        slug: 'brandix',
        name: 'Brandix',
        country: 'TG',
        image: '/images/brands/brand-5.png',
        latitude: 6.1319,
        longitude: 1.2228,
        shopId: 105,
    },
    {
        id: 6,
        slug: 'abs-brand',
        name: 'ABS-Brand',
        country: 'NG',
        image: '/images/brands/brand-6.png',
        latitude: 6.5244,
        longitude: 3.3792,
        shopId: 106,
    },
    {
        id: 7,
        slug: 'great-circle',
        name: 'GreatCircle',
        country: 'BJ',
        image: '/images/brands/brand-7.png',
        latitude: 6.3703,
        longitude: 2.3912,
        shopId: 107,
    },
    {
        id: 8,
        slug: 'just-romb',
        name: 'JustRomb',
        country: 'TG',
        image: '/images/brands/brand-8.png',
        latitude: 6.1256,
        longitude: 1.2100,
        shopId: 108,
    },
    {
        id: 9,
        slug: 'fast-wheels',
        name: 'FastWheels',
        country: 'CI',
        image: '/images/brands/brand-9.png',
        latitude: 5.3600,
        longitude: -4.0083,
        shopId: 109,
    },
    {
        id: 10,
        slug: 'stroyka-x',
        name: 'Stroyka-X',
        country: 'DE',
        image: '/images/brands/brand-10.png',
        latitude: 50.1109,
        longitude: 8.6821,
        shopId: 110,
    },
    {
        id: 11,
        slug: 'mission-51',
        name: 'Mission-51',
        country: 'DE',
        image: '/images/brands/brand-11.png',
        latitude: 48.1351,
        longitude: 11.5820,
        shopId: 111,
    },
    {
        id: 12,
        slug: 'fuel-corp',
        name: 'FuelCorp',
        country: 'FR',
        image: '/images/brands/brand-12.png',
        latitude: 48.8566,
        longitude: 2.3522,
        shopId: 112,
    },
    {
        id: 13,
        slug: 'red-gate',
        name: 'RedGate',
        country: 'SN',
        image: '/images/brands/brand-13.png',
        latitude: 14.6928,
        longitude: -17.4467,
        shopId: 113,
    },
    {
        id: 14,
        slug: 'blocks',
        name: 'Blocks',
        country: 'TG',
        image: '/images/brands/brand-14.png',
        latitude: 6.1700,
        longitude: 1.2050,
        shopId: 114,
    },
    {
        id: 15,
        slug: 'blackbox',
        name: 'BlackBox',
        country: 'NG',
        image: '/images/brands/brand-15.png',
        latitude: 9.0579,
        longitude: 7.4951,
        shopId: 115,
    },
    {
        id: 16,
        slug: 'square-garage',
        name: 'SquareGarage',
        country: 'BJ',
        image: '/images/brands/brand-16.png',
        latitude: 6.4025,
        longitude: 2.5186,
        shopId: 116,
    },
    {
        id: 17,
        slug: 'sunset',
        name: 'Sunset',
        country: 'TG',
        image: '/images/brands/brand-1.png',
        latitude: 6.1450,
        longitude: 1.2200,
        shopId: 117,
    },
    {
        id: 18,
        slug: 'specter',
        name: 'Specter',
        country: 'CN',
        image: '/images/brands/brand-2.png',
        latitude: 31.2304,
        longitude: 121.4737,
        shopId: 118,
    },
    {
        id: 19,
        slug: 'no-name',
        name: 'No Name',
        country: 'CN',
        image: '/images/brands/brand-3.png',
        latitude: 39.9042,
        longitude: 116.4074,
        shopId: 119,
    },
];
