/* eslint-disable import/prefer-default-export */

// application
import { IShop } from '~/interfaces/shop';

export const shops: IShop[] = [
    {
        id: 101,
        slug: 'aim-parts-shop',
        name: 'AimParts Auto',
        image: '/images/shops/shop-1.jpg',
        country: 'TG',
        latitude: 6.1375,
        longitude: 1.2123,
        city: 'Lomé',
        address: '123 Avenue de la Paix',
        phone: '+228 12 34 56 78',
        email: 'contact@aimparts.tg',
        whatsapp: '+228 12 34 56 78',
        rating: 4.5,
        reviewCount: 127,
    },
    {
        id: 102,
        slug: 'wind-engine-shop',
        name: 'WindEngine Pro',
        image: '/images/shops/shop-2.jpg',
        country: 'TG',
        latitude: 6.1800,
        longitude: 1.2300,
        city: 'Lomé',
        address: '456 Rue du Commerce',
        phone: '+228 23 45 67 89',
        email: 'info@windengine.tg',
        whatsapp: '+228 23 45 67 89',
        rating: 4.2,
        reviewCount: 89,
    },
    {
        id: 103,
        slug: 'turbo-electric-shop',
        name: 'TurboElectric Ghana',
        image: '/images/shops/shop-3.jpg',
        country: 'GH',
        latitude: 5.6037,
        longitude: -0.1870,
        city: 'Accra',
        address: '789 Industrial Area',
        phone: '+233 20 123 4567',
        email: 'sales@turboelectric.com.gh',
        whatsapp: '+233 20 123 4567',
        rating: 4.8,
        reviewCount: 156,
    },
    {
        id: 104,
        slug: 'start-one-shop',
        name: 'StartOne Solutions',
        image: '/images/shops/shop-4.jpg',
        country: 'GH',
        latitude: 6.6885,
        longitude: -1.6244,
        city: 'Kumasi',
        address: '321 Tech Park Road',
        phone: '+233 30 987 6543',
        email: 'hello@startone.com.gh',
        whatsapp: '+233 30 987 6543',
        rating: 4.6,
        reviewCount: 93,
    },
    {
        id: 105,
        slug: 'brandix-shop',
        name: 'Brandix Automotive',
        image: '/images/shops/shop-5.jpg',
        country: 'TG',
        latitude: 6.1319,
        longitude: 1.2228,
        city: 'Lomé',
        address: '654 Auto Market',
        phone: '+228 98 76 54 32',
        email: 'info@brandix.tg',
        whatsapp: '+228 98 76 54 32',
        rating: 4.3,
        reviewCount: 74,
    },
    {
        id: 106,
        slug: 'abs-brand-shop',
        name: 'ABS-Brand Nigeria',
        image: '/images/shops/shop-6.jpg',
        country: 'NG',
        latitude: 6.5244,
        longitude: 3.3792,
        city: 'Lagos',
        address: '987 Victoria Island',
        phone: '+234 801 234 5678',
        email: 'lagos@absbrand.ng',
        whatsapp: '+234 801 234 5678',
        rating: 4.7,
        reviewCount: 201,
    },
    {
        id: 107,
        slug: 'great-circle-shop',
        name: 'GreatCircle Benin',
        image: '/images/shops/shop-7.jpg',
        country: 'BJ',
        latitude: 6.3703,
        longitude: 2.3912,
        city: 'Cotonou',
        address: '147 Route des Pêches',
        phone: '+229 21 30 40 50',
        email: 'benin@greatcircle.bj',
        whatsapp: '+229 21 30 40 50',
        rating: 4.4,
        reviewCount: 68,
    },
    {
        id: 108,
        slug: 'just-romb-shop',
        name: 'JustRomb Togo',
        image: '/images/shops/shop-8.jpg',
        country: 'TG',
        latitude: 6.1256,
        longitude: 1.2100,
        city: 'Lomé',
        address: '258 Bè District',
        phone: '+228 90 12 34 56',
        email: 'contact@justromb.tg',
        whatsapp: '+228 90 12 34 56',
        rating: 4.1,
        reviewCount: 45,
    },
];
